name: Release
on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: npm-publish # ties to the protected env above
    permissions:
      contents: read
      id-token: write # required for OIDC
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: "package.json"
          registry-url: "https://registry.npmjs.org"
      - run: yarn install
      - run: yarn build
      - run: yarn test
      - run: npm publish
